version: '3'
services: 
  database:
    build: ./database
    ports:
      - 3307:3306
  backend:
    build: ./backend
    volumes:
      - .\backend:/usr/src/app
    ports:
      - 3000:3000
    depends_on: 
      - database
    environment:
      - NODE_ENV_HOST=database
    command: >
      sh -c "/app/wait-for-it.sh database:3306 && npm start"
